spring:
  application:
    name: rentpay-management

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#  datasource:
#    url: jdbc:h2:mem:rentpaydb;DB_CLOSE_DELAY=-1;MODE=MySQL
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

  datasource:
    url: jdbc:mysql://localhost:3306/rentpay_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: rentpay_user
    password: RentPay@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect



  #  security:
  #    user:
  #      name: user
  #      password: password123

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_APP_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cashfree:
  clientId: ${clientId}
  clientSecret: ${clientSecret}
  cashfreeBaseUrl: ${cashfreeBaseUrl}

app:
  security:
    user:
      username: ${APP_USER}
      password: ${APP_PASSWORD}
      role: ${APP_ROLE}

notify_url: ${NOTIFY_URL}
return_url: ${RETURN_URL}
private_key: ${PRIVATE_SECRET_KEY}

